/**
 * Lessons model test (#1273): toast-stats now uses the Red Barkeep lessons
 * model (taverns-red/red-barkeep#41/#42) — kebab-slug.md files with
 * date/tier/summary frontmatter, a GENERATED INDEX.md, and the session-judged
 * shell loader. Replaces the retired custom TS lessons subsystem.
 */
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync, writeFileSync, rmSync } from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

const ROOT = process.cwd()
const LESSONS_DIR = path.join(ROOT, 'tasks/lessons')

const tierFiles = (tier: string): string[] => {
  try {
    return readdirSync(path.join(LESSONS_DIR, tier)).filter(
      f => f.endsWith('.md') && f !== 'INDEX.md' && f !== 'README.md'
    )
  } catch {
    return []
  }
}
const allLessons = (): { tier: string; file: string }[] =>
  ['rules', 'lessons', 'incidents'].flatMap(t =>
    tierFiles(t).map(file => ({ tier: t, file }))
  )

describe('Lessons follow the Red Barkeep model (#1273)', () => {
  it('no lesson uses a numeric filename prefix (the retired, collision-prone scheme)', () => {
    for (const { file } of allLessons()) expect(file, file).not.toMatch(/^\d+-/)
  })

  it('every lesson declares date/tier/summary frontmatter', () => {
    for (const { tier, file } of allLessons()) {
      const body = readFileSync(path.join(LESSONS_DIR, tier, file), 'utf8')
      expect(body.startsWith('---\n'), `${file} has no frontmatter`).toBe(true)
      expect(body, `${file} missing date`).toMatch(/^date:\s*\S/m)
      expect(body, `${file} missing tier`).toMatch(/^tier:\s*\S/m)
      expect(body, `${file} missing summary`).toMatch(/^summary:\s*\S/m)
    }
  })

  it('INDEX.md is generated and in sync (the stock drift gate)', () => {
    const index = readFileSync(path.join(LESSONS_DIR, 'INDEX.md'), 'utf8')
    expect(index).toContain('Generated by scripts/lessons-index.sh')
    // `--check` exits non-zero on drift or a lesson missing frontmatter.
    expect(() =>
      execFileSync(
        'bash',
        [path.join(ROOT, 'scripts/lessons-index.sh'), '--check'],
        {
          cwd: ROOT,
          env: { ...process.env, LESSONS_DIR: 'tasks/lessons' },
        }
      )
    ).not.toThrow()
  })

  it('relevant-lessons.sh emits the catalog (session-judged, large corpus)', () => {
    const bodyFile = path.join(os.tmpdir(), `ts-issue-body-${process.pid}.txt`)
    writeFileSync(
      bodyFile,
      'chore: a sprint with no manifest\nchore\nnothing here\n'
    )
    try {
      const out = execFileSync(
        'bash',
        [path.join(ROOT, 'scripts/relevant-lessons.sh'), '999'],
        {
          cwd: ROOT,
          encoding: 'utf8',
          env: { ...process.env, ISSUE_BODY_FILE: bodyFile },
        }
      )
        .trim()
        .split('\n')
      // Large corpus (160+): the loader hands over the INDEX.md catalog plus the
      // single newest-by-date lesson — it does NOT bulk-emit every lesson.
      expect(out.some(l => l.endsWith('INDEX.md'))).toBe(true)
      const lessonLines = out.filter(
        l => l.includes('/lessons/lessons/') && l.endsWith('.md')
      )
      expect(lessonLines).toHaveLength(1)
    } finally {
      rmSync(bodyFile, { force: true })
    }
  })
})
