/**
 * Lessons model test (#1273): toast-stats now uses the Red Barkeep lessons
 * model (taverns-red/red-barkeep#41/#42) — kebab-slug.md files with
 * date/tier/summary frontmatter, a GENERATED INDEX.md, and the session-judged
 * shell loader. Replaces the retired custom TS lessons subsystem.
 */
import { describe, it, expect } from 'vitest'
import { execFileSync, spawnSync } from 'node:child_process'
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  rmSync,
} from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

const ROOT = process.cwd()
const LESSONS_DIR = path.join(ROOT, 'tasks/lessons')

const tierFiles = (tier: string): string[] => {
  try {
    return readdirSync(path.join(LESSONS_DIR, tier)).filter(
      f => f.endsWith('.md') && f !== 'INDEX.md' && f !== 'README.md'
    )
  } catch {
    return []
  }
}
const allLessons = (): { tier: string; file: string }[] =>
  ['rules', 'lessons', 'incidents'].flatMap(t =>
    tierFiles(t).map(file => ({ tier: t, file }))
  )

describe('Lessons follow the Red Barkeep model (#1273)', () => {
  it('no lesson uses a numeric filename prefix (the retired, collision-prone scheme)', () => {
    for (const { file } of allLessons()) expect(file, file).not.toMatch(/^\d+-/)
  })

  it('every lesson declares date/tier/summary frontmatter', () => {
    for (const { tier, file } of allLessons()) {
      const body = readFileSync(path.join(LESSONS_DIR, tier, file), 'utf8')
      expect(body.startsWith('---\n'), `${file} has no frontmatter`).toBe(true)
      expect(body, `${file} missing date`).toMatch(/^date:\s*\S/m)
      expect(body, `${file} missing tier`).toMatch(/^tier:\s*\S/m)
      expect(body, `${file} missing summary`).toMatch(/^summary:\s*\S/m)
    }
  })

  it('INDEX.md is generated and in sync (the stock drift gate)', () => {
    const index = readFileSync(path.join(LESSONS_DIR, 'INDEX.md'), 'utf8')
    expect(index).toContain('Generated by scripts/lessons-index.sh')
    // `--check` exits non-zero on drift or a lesson missing frontmatter.
    expect(() =>
      execFileSync(
        'bash',
        [path.join(ROOT, 'scripts/lessons-index.sh'), '--check'],
        {
          cwd: ROOT,
          env: { ...process.env, LESSONS_DIR: 'tasks/lessons' },
        }
      )
    ).not.toThrow()
  })

  it('relevant-lessons.sh emits the catalog (session-judged, large corpus)', () => {
    const bodyFile = path.join(os.tmpdir(), `ts-issue-body-${process.pid}.txt`)
    writeFileSync(
      bodyFile,
      'chore: a sprint with no manifest\nchore\nnothing here\n'
    )
    try {
      const out = execFileSync(
        'bash',
        [path.join(ROOT, 'scripts/relevant-lessons.sh'), '999'],
        {
          cwd: ROOT,
          encoding: 'utf8',
          env: { ...process.env, ISSUE_BODY_FILE: bodyFile },
        }
      )
        .trim()
        .split('\n')
      // Large corpus (160+): the loader hands over the INDEX.md catalog plus the
      // single newest-by-date lesson — it does NOT bulk-emit every lesson.
      expect(out.some(l => l.endsWith('INDEX.md'))).toBe(true)
      const lessonLines = out.filter(
        l => l.includes('/lessons/lessons/') && l.endsWith('.md')
      )
      expect(lessonLines).toHaveLength(1)
    } finally {
      rmSync(bodyFile, { force: true })
    }
  })

  it('relevant-lessons.sh survives a corpus larger than the pipe buffer (#1667)', () => {
    // The newest-lesson pick pipes the whole corpus through `sort -r` into a
    // consumer that wants one line. Under `set -o pipefail`, a consumer that
    // exits early (`head -1`) SIGPIPEs sort once its output exceeds the pipe
    // buffer (64 KiB) and the script dies with 141. ~150 KiB of sort output
    // (600 long names) makes that deterministic rather than a timing race.
    const dir = mkdtempSync(path.join(os.tmpdir(), 'ts-lessons-1667-'))
    try {
      mkdirSync(path.join(dir, 'lessons'))
      writeFileSync(path.join(dir, 'INDEX.md'), '# index\n')
      const pad = 'a'.repeat(220)
      for (let i = 1; i <= 600; i++) {
        const day = String((i % 28) + 1).padStart(2, '0')
        writeFileSync(
          path.join(
            dir,
            'lessons',
            `lesson-${String(i).padStart(4, '0')}-${pad}.md`
          ),
          `---\ndate: 2026-01-${day}\ntier: lesson\nsummary: x\n---\n`
        )
      }
      const bodyFile = path.join(dir, 'body.txt')
      writeFileSync(bodyFile, 'chore: no manifest\n')
      const res = spawnSync(
        'bash',
        [path.join(ROOT, 'scripts/relevant-lessons.sh'), '999'],
        {
          cwd: ROOT,
          encoding: 'utf8',
          env: { ...process.env, LESSONS_DIR: dir, ISSUE_BODY_FILE: bodyFile },
        }
      )
      expect(res.status, res.stderr).toBe(0)
      expect(res.stdout.trim().split('\n')).toEqual([
        path.join(dir, 'INDEX.md'),
        // Newest date is 2026-01-28 (i % 28 === 27); sort -r on the whole
        // "date<TAB>path" line breaks the tie by the greatest path.
        path.join(dir, 'lessons', `lesson-0587-${pad}.md`),
      ])
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })
})
