/**
 * SEO static-asset generator core (#782, epic #785, finding F-SA2).
 *
 * Single source of truth for `frontend/public/robots.txt` and
 * `frontend/public/sitemap.xml`. Pure string builders here; the IO entry point
 * (`scripts/generate-seo-assets.ts`) writes the files and a `--check` mode +
 * the `scripts/lib/__tests__/seoAssets.test.ts` drift guard keep the committed
 * artifacts in lockstep with this manifest. Mirrors the `lessonsIndex` pattern.
 *
 * Only stable, parameter-free public routes belong in the sitemap. Per-entity
 * routes (`/district/:id`, `/region/:n`, `/club/:id`) are data-dependent and
 * cannot be enumerated statically — crawlers reach them by following links
 * from the indexed pages.
 */

/** Canonical production origin — no trailing slash. Matches the `og:url` /
 *  `<link rel="canonical">` host shipped in `frontend/index.html` (#778). */
export const ORIGIN = 'https://ts.taverns.red'

/** One stable public route. `path` is root-relative and begins with `/`. */
export interface PublicRoute {
  path: string
}

/**
 * The stable, indexable public routes (audit F-SA2: Districts, Methodology,
 * History, Regions, Awards). Keep in sync with the parameter-free routes in
 * `frontend/src/App.tsx`; the drift-guard test fails if the committed sitemap
 * stops matching this list.
 */
export const PUBLIC_ROUTES: readonly PublicRoute[] = [
  { path: '/' }, // Districts (landing)
  { path: '/methodology' },
  { path: '/history' },
  { path: '/regions' },
  { path: '/awards' },
  { path: '/mcp' }, // MCP-server install page (#1165)
]

/** Absolute URL for a route path (`/` → `${ORIGIN}/`). */
function absoluteUrl(path: string): string {
  return `${ORIGIN}${path}`
}

/** Build the `robots.txt` body: allow all crawlers, advertise the sitemap. */
export function buildRobotsTxt(): string {
  return [
    '# Toast Stats — Toastmasters District Performance',
    '# Generated by scripts/generate-seo-assets.ts.',
    '# Do not hand-edit: run `npm run seo:generate` to regenerate.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n')
}

/** Build the `sitemap.xml` body — one `<url><loc>` per stable public route. */
export function buildSitemapXml(): string {
  const urls = PUBLIC_ROUTES.map(
    route => `  <url>\n    <loc>${absoluteUrl(route.path)}</loc>\n  </url>`
  ).join('\n')
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    '</urlset>',
    '',
  ].join('\n')
}
