#!/usr/bin/env bash
# lessons-index.sh — generate INDEX.md from lesson frontmatter (#41).
#
# The index is the catalog the session judges relevance against (see the
# session-judged loader, #42). It is GENERATED, never hand-edited, so it can
# never silently miss a lesson. Each lesson carries YAML frontmatter:
#
#   ---
#   date: 2026-06-28          # ISO; drives recency + sort (replaces the old number)
#   tier: lesson              # rules | lesson | incident
#   summary: <one line>       # what the session judges relevance from
#   tags: [a, b]              # optional
#   legacy_id: "086"          # optional; preserves old #086/L086 cross-refs
#   ---
#
# Output: $LESSONS_DIR/INDEX.md, grouped by tier (rules, lessons, incidents),
# each sorted newest-first by date, one line per lesson.
#
#   lessons-index.sh            # (re)write INDEX.md
#   lessons-index.sh --check    # exit non-zero if INDEX.md is stale (CI drift gate)
#   lessons-index.sh --stdout   # print the index instead of writing
#
#   Env: LESSONS_DIR (default: tasks/lessons)
set -euo pipefail

LESSONS_DIR="${LESSONS_DIR:-tasks/lessons}"
MODE=write
case "${1:-}" in
  --check)  MODE=check ;;
  --stdout) MODE=stdout ;;
  "")       ;;
  *) echo "lessons-index: unknown arg: $1" >&2; exit 2 ;;
esac

[[ -d "$LESSONS_DIR" ]] || { echo "lessons-index: no such dir: $LESSONS_DIR" >&2; exit 2; }

# Read a scalar frontmatter value: fm <file> <key>. Frontmatter is the YAML block
# between the first `---` line and the next `---`.
fm() {
  awk -v k="$2" '
    NR==1 && $0=="---" { f=1; next }
    f && $0=="---" { exit }
    f && index($0, k ":")==1 { v=$0; sub("^" k ":[[:space:]]*", "", v); print v; exit }
  ' "$1"
}

# Canonical tier order/labels.
canon_tier() {
  case "$1" in
    rule|rules)         echo rules ;;
    lesson|lessons)     echo lessons ;;
    incident|incidents) echo incidents ;;
    *)                  echo lessons ;;   # default bucket
  esac
}

# Collect rows as "tier\tdate\tfilename\tsummary".
rows=""
while IFS= read -r f; do
  base="$(basename "$f")"
  [[ "$base" == "INDEX.md" || "$base" == "README.md" ]] && continue
  date="$(fm "$f" date)"; summary="$(fm "$f" summary)"; tier="$(fm "$f" tier)"
  [[ -z "$tier" ]] && tier="$(basename "$(dirname "$f")")"   # fall back to the dir
  tier="$(canon_tier "$tier")"
  if [[ -z "$date" ]]; then echo "lessons-index: $f missing 'date' frontmatter" >&2; exit 3; fi
  if [[ -z "$summary" ]]; then echo "lessons-index: $f missing 'summary' frontmatter" >&2; exit 3; fi
  rows+="${tier}"$'\t'"${date}"$'\t'"${base}"$'\t'"${summary}"$'\n'
# `LC_ALL=C` on both sorts (#1370): collation is locale-dependent, so the same
# corpus generated a DIFFERENT index on macOS than on the ubuntu CI runner —
# `en_CA.UTF-8` folds case (`IA-tab-strip…` lands among the `i`s) while CI's C
# locale orders by byte (`I` < `a`, so it leads). The drift gate then failed for
# whoever regenerated on the other platform, blaming a file they never touched.
# Scoped to `sort` rather than exported, so awk still reads the UTF-8 summaries
# (em-dashes, curly quotes) as characters.
done < <(find "$LESSONS_DIR" -name '*.md' | LC_ALL=C sort)

render() {
  printf '<!-- Generated by scripts/lessons-index.sh — do not edit by hand. -->\n'
  printf '# Lessons index\n'
  local tier label
  for tier in rules lessons incidents; do
    case "$tier" in
      rules)     label="rules (always loaded)" ;;
      lessons)   label="lessons (manifest-pinned + session-judged)" ;;
      incidents) label="incidents (ref-only — pull when relevant)" ;;
    esac
    # Tier rows, date desc (newest first), ties broken on filename (field 3).
    # `-k3,3` states the tie-break instead of leaning on sort's last-resort
    # WHOLE-LINE comparison, which reaches the filename only because of the
    # current field order and would silently switch to the summary if the row
    # layout ever changed (and vanishes entirely if anyone adds `-s`).
    local body
    body="$(printf '%s' "$rows" | awk -F'\t' -v t="$tier" '$1==t' | LC_ALL=C sort -t$'\t' -k2,2r -k3,3)"
    [[ -z "$body" ]] && continue
    printf '\n## %s\n' "$label"
    printf '%s\n' "$body" | while IFS=$'\t' read -r _ d file summ; do
      [[ -n "$file" ]] && printf -- '- `%s` — %s  (%s)\n' "$file" "$summ" "$d"
    done
  done
}

out="$(render)"

case "$MODE" in
  stdout) printf '%s\n' "$out" ;;
  write)  printf '%s\n' "$out" > "$LESSONS_DIR/INDEX.md"
          echo "lessons-index: wrote $LESSONS_DIR/INDEX.md" >&2 ;;
  check)  if [[ "$(cat "$LESSONS_DIR/INDEX.md" 2>/dev/null)" == "$out" ]]; then
            exit 0
          else
            echo "lessons-index: $LESSONS_DIR/INDEX.md is stale — run scripts/lessons-index.sh" >&2
            exit 1
          fi ;;
esac
